// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiC8ruwfad4aQkChWHvpJYlNW3g0Q3Ui4',
    appId: '1:591212866781:android:9a5968b347c8273ff6ff34',
    messagingSenderId: '591212866781',
    projectId: 'fitness-d5256',
    storageBucket: 'fitness-d5256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1J8xIc-3bRghsIIJR2Tmr7z7WaazIcpY',
    appId: '1:591212866781:ios:b3bd514bdfd73bdcf6ff34',
    messagingSenderId: '591212866781',
    projectId: 'fitness-d5256',
    storageBucket: 'fitness-d5256.firebasestorage.app',
    androidClientId: '591212866781-n885rl7rovp8c1elq9jn4amqikm20idj.apps.googleusercontent.com',
    iosClientId: '591212866781-db7qd6ca481cq24bfdfhsda37bmtikhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1J8xIc-3bRghsIIJR2Tmr7z7WaazIcpY',
    appId: '1:591212866781:ios:b3bd514bdfd73bdcf6ff34',
    messagingSenderId: '591212866781',
    projectId: 'fitness-d5256',
    storageBucket: 'fitness-d5256.firebasestorage.app',
    androidClientId: '591212866781-n885rl7rovp8c1elq9jn4amqikm20idj.apps.googleusercontent.com',
    iosClientId: '591212866781-db7qd6ca481cq24bfdfhsda37bmtikhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt7GbNZMwPP0MEb7bWR1_TILs_dZn8E9I',
    appId: '1:591212866781:web:a61043085522ef78f6ff34',
    messagingSenderId: '591212866781',
    projectId: 'fitness-d5256',
    authDomain: 'fitness-d5256.firebaseapp.com',
    storageBucket: 'fitness-d5256.firebasestorage.app',
    measurementId: 'G-NZMDES6094',
  );
}
